from insurance_multi_agent.agents.prompts import ENTITY_EXTRACTION_PROMPT as ENTITY_EXTRACTION_PROMPT
from insurance_multi_agent.agents.prompts import CLAUSE_SUMMARIZATION_PROMPT as CLAUSE_SUMMARIZATION_PROMPT
from insurance_multi_agent.agents.prompts import RISK_ANALYSIS_PROMPT as RISK_ANALYSIS_PROMPT
from insurance_multi_agent.agents.entity_extractor_agent import EntityExtractorAgent as EntityExtractorAgent
from insurance_multi_agent.agents.risk_analyzer_agent import RiskAnalyzerAgent as RiskAnalyzerAgent
from insurance_multi_agent.agents.summary_agent import SummaryAgent as SummaryAgent 